site_name: Open Mafia Engine
theme:
  name: "material"
# Plugins: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
plugins:
  - search
  - autorefs
  - mkdocstrings
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:pymdownx.emoji.gemoji
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
nav:
  - Home: index.md
  - "User Guide":
      - "Main Concepts": user_guide/concepts.md
      - "Game State": user_guide/state.md
      - "Abilities": user_guide/abilities.md
      - "Outcomes": user_guide/outcomes.md
      - "Prefabs": user_guide/prefabs.md
  - "Reference": reference/index.md
  - "Development":
      - "Installing for dev": development/installing_dev.md
      - "Writing Docs": development/writing_docs.md
  - About: about.md
