site_name: Open Mafia Engine
nav:
  - Home: index.md
  - "User Guide":
      - "Main Concepts": user_guide/concepts.md
      - "Game State": user_guide/state.md
      - "Abilities": user_guide/abilities.md
      - "Prefabs": user_guide/prefabs.md
  - "Development":
      - "Installing for dev": development/installing_dev.md
      - "Writing Docs": development/writing_docs.md
  - About: about.md
