version: 1.0
name: "Vanilla Mafia"
phases:
  - day
  - night
alignments:
  - name: town
    wincon:
      type: alignments_eliminated
      alignments: [mafia]
  - name: mafia
    wincon:
      type: alignments_majority
      alignments: [mafia]
roles:
  - name: Citizen
    desc: |
      You are just a Citizen. Your only tool is the vote.
      You win when all the Mafia are eliminated.
    alignment: town
    abilities:
      - name: Vote
        type: lynch_vote
        desc: Vote to lynch the target.
        constraints:
          - type: phase
            phases: [day]
        # NOTE: Will appear as
        # [Day] Vote (target): Vote to lynch the target.
  - name: Mafioso
    desc: |
      You are a Mafioso. You may privately talk with your teammates.
      You win when the Mafia outnumbers the Citizens.
    alignment: mafia
    abilities:
      - "lynch_vote"
      - name: Mafia Kill
        type: kill
        desc: Kill the target. Only one Mafioso may use this per night.
        constraints:
          - type: key_phase_limited
            key: mafia
            phases: [night]
            uses: 1
        # NOTE: Will appear as
        # [Night, Mafia] Mafia Kill (target): Kill the target. Only one Mafioso may use this per night.
triggers:
  - name: "Lynch on day end"
    type: "phase_end_lynch"
game_variants:
  - name: "5 players"
    players: 5
    roles_counts:
      - name: Citizen
        qty: 4
      - name: Mafioso
        qty: 1
  - name: "6 players"
    players: 6
    roles_counts:
      - name: Citizen
        qty: 5
      - name: Mafioso
        qty: 1
  - name: "7 players"
    players: 7
    roles_counts:
      - name: Citizen
        qty: 5
      - name: Mafioso
        qty: 2
