# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package "open_mafia_engine"

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.7
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        ignore_dev_requirements: "yes"
